/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutUsersCreateRouteImport } from './routes/_layout/users-create'
import { Route as LayoutUsersUserIdRouteImport } from './routes/_layout/users-$userId'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersCreateRoute = LayoutUsersCreateRouteImport.update({
  id: '/users-create',
  path: '/users-create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersUserIdRoute = LayoutUsersUserIdRouteImport.update({
  id: '/users-$userId',
  path: '/users-$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/users': typeof LayoutUsersRoute
  '/users-$userId': typeof LayoutUsersUserIdRoute
  '/users-create': typeof LayoutUsersCreateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/users': typeof LayoutUsersRoute
  '/users-$userId': typeof LayoutUsersUserIdRoute
  '/users-create': typeof LayoutUsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/users-$userId': typeof LayoutUsersUserIdRoute
  '/_layout/users-create': typeof LayoutUsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/users' | '/users-$userId' | '/users-create'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/users' | '/users-$userId' | '/users-create'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/users'
    | '/_layout/users-$userId'
    | '/_layout/users-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users-create': {
      id: '/_layout/users-create'
      path: '/users-create'
      fullPath: '/users-create'
      preLoaderRoute: typeof LayoutUsersCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users-$userId': {
      id: '/_layout/users-$userId'
      path: '/users-$userId'
      fullPath: '/users-$userId'
      preLoaderRoute: typeof LayoutUsersUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutUsersUserIdRoute: typeof LayoutUsersUserIdRoute
  LayoutUsersCreateRoute: typeof LayoutUsersCreateRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutUsersUserIdRoute: LayoutUsersUserIdRoute,
  LayoutUsersCreateRoute: LayoutUsersCreateRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
